### ISSUE TITLE
Make compatible with newest Celluloid version

### ISSUE THREAD

**Issue by myobie** [celluloid/dcell#106]
Just playing around with DCell and noticed that it doesn't work with the latest Celluloid 0.17.2.

Get a `NameError: uninitialized constant Celluloid::ActorProxy` from `require 'dcell'`

How far have the projects diverged? Is this something I could try to help with or is it super big changes?

I looked a bit, but I didn't quickly discern the answer.

**Comment by digitalextremist** [comment]
For right now, are you able to use `require 'celluloid/current'`? I've added the changed object names to `deprecate.rb` and am cutting a point release for this.

**Comment by myobie** [comment]
I was not able to require current (that is what I was doing before trying to include dcell). It seems that cell pins itself to 0.16.x, but even going back to that I was not able to get it to work. Is there a .pre release I can test for you?

**Comment by niamster** [comment]
@myobie, can you provide the output of 'bundle show'? BTW how do you launch your dcell-powered app?

**Comment by myobie** [comment]
@niamster Here is the output from `bundle show`: https://gist.github.com/myobie/afa3c2fbaf2d9c490e2b

Right now I have a simple rake task to require all my code and then `IRB.start`. I've gotten a simple codebase using just celluloid going and I was going to use dcell to reference/materialize actors first in other processes and then later on other machines. I really just wanted to very quickly show a concept working that I would probably later implement with akka. I think dcell could be great for prototyping actor systems that might eventually have a life in another actor system.

**Comment by gxbe** [comment]
I'm having the exact same issue, was forced to downgrade celluloid to "~> 0.16.0" but then the library http required by dcell is frozen at 5.0.0 while current is 0.8.4.

**Comment by jamesaspinwall** [comment]
I am also waiting for DCell to catch up to Celluloid. I have tried several ways to make it work with Reel, and always get some compatibility issue. I really like this set of libraries, but it is broken. I hope you can update it soon.

**Comment by digitalextremist** [comment]
Noted, and thanks for your patience. You are right, and as the repositories are omnibus-style merged, this will happen.

**Comment by GrandVizierOlaf** [comment]
Is there an update to this? I'm trying to merge a project that uses dcell with one that already uses celluloid and I'm seeing messages like this no matter how I set up my Gemfile or require statements:

> I, [2016-02-09T16:06:45.888779 #3062]  INFO -- : Celluloid 0.17.2 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
/home/someone/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2064:in `raise_if_conflicts': Unable to activate dcell-0.16.1, because celluloid-0.17.2 conflicts with celluloid (~> 0.16.0) (Gem::LoadError)

**Comment by GrandVizierOlaf** [comment]
Never mind, I had apparently installed some of the celluloid gems with the gem command, rather than Bundler and it was confusing things. I uninstalled everything, downgraded my zmq to 3.2.5, used Bundler, and I'm back in business.

**Comment by tarcieri** [comment]
@GrandVizierOlaf awesome to hear that

**Comment by colstrom** [comment]
Looks like this is still open. If someone can toss me a list of what needs to be done, I'd be willing to work on this.

**Comment by myobie** [comment]
I'm closing this since it's been so long.
