### ISSUE TITLE
Clean up the registry API

### ISSUE THREAD

**Issue by aflatter** [celluloid/dcell#49]
As per celluloid/floss#14, the registry API is to be refactored. As per a discussion with @tarcieri on IRC, this includes the following changes:

#### A new API for implementing a registry.

```ruby
class RegistryAdapter
    def initialize(options = {})
    end

    def get(namespace, key)
    end

    def set(namespace, key, value)
    end

    def keys(namespace)
    end

    def clear(namespace)
    end
end
```

A registry should be an actor too.

#### Refactor `Global` and `Directory`

Provide a `NamespaceProxy` to DRY this up:

```ruby
global = registry[:global] # => DCell::Registry::NamespaceProxy
global[:foo] = :bar
```

One of the following:

  * Provide `DCell.global[:foo]` and `DCell.directory[:bar]` (or `DCell[:global, :foo]`)
  * Use `Node[:bar]` for the directory and `DCell[:bar]` for globals.

Opinions?

**Comment by niamster** [comment]
I've cleaned up a bit the Registry API in pull request #91 
Though, as @tarcieri I have doubts whether those should be actors. I noticed a quite noticeable overhead in my stress testing.
Probably a particular implementation should be an actor if registry BE library can't handle asynchronous requests. Mainly DCell does read access so I don't see a good reason to serialize access.

**Comment by niamster** [comment]
No feedback means everybody satisfied with current registry API?
