### ISSUE TITLE
Block when acessing actor from foreign node

### ISSUE THREAD

**Issue by TiagoCardoso1983** [celluloid/dcell#64]
I'm using DCell with redis registry. I've started these two scripts where both nodes were registered the first time to redis. Through it, they are sharing an access address and they communicate. 

Problem is, if I stop one script, everytime the running script tries to access it, it blocks.

```ruby
DCell::Node["app"] 
#=> #<DCell::Node[app] @addr="tcp://127.0.0.1:8888"> 
# Important, the node is there, but since the respective script is running, no actor is reachable. 
DCell::Node["app"]["time_server"]
#=> Connected to "app"
......
```

It seems that this happens because the stopped script has registered itself in redis the first time it ran, but it never unregistered itself when it stopped. Hence, the second script still gets the reference to its address.

So the question is, is there a way to unregister itself from the cluster on process stopped? Some way to prevent the block from happening?

**Comment by niamster** [comment]
In current master there is a possibility to ping(and get latency accordingly) remote node before starting any communication(that should be done explicitly).
Also when a local instance of a node(bound to remote one) is created, it checks current value of TTL. If remote node didn't update it within a grace period then exception is raised and creation is aborted.
If the remote nodes goes down and doesn't answer within the grace period then the client will raise an exception.
