### ISSUE TITLE
[Trivial] Prerequisites need on Introduction page. 

### ISSUE THREAD

**Issue by hiroyuki-sato** [celluloid/dcell#65]
Hello developers. 

I think It is good idea to add Prerequisites page link on this page.
https://github.com/celluloid/dcell

Because I didn't know It's need redis-server until execute itchy.rb sample
And I couldn't find Redis keyword on that page. 

Could you add the following block on that page.?

Prerequisites
-------------

Read [Prerequisites](https://github.com/celluloid/dcell/wiki/Prerequisites) page.

## Execution result

    % ruby itchy.rb 
    D, [2014-07-08T18:07:03.363530 #3568] DEBUG -- : Terminating 1 actor...
    /path/to/ruby/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/client.rb:276:in `rescue in establish_connection': Error connecting to Redis on 127.0.0.1:6379 (ECONNREFUSED) (Redis::CannotConnectError)
    	from /path/to/ruby/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/client.rb:271:in `establish_connection'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/client.rb:69:in `connect'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/client.rb:290:in `ensure_connected'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/client.rb:177:in `block in process'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/client.rb:256:in `logging'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/client.rb:176:in `process'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/client.rb:84:in `call'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis.rb:1747:in `block in hset'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis.rb:36:in `block in synchronize'
    	from /path/to/ruby/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis.rb:36:in `synchronize'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis.rb:1746:in `hset'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/redis-namespace-1.3.1/lib/redis/namespace.rb:317:in `method_missing'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/dcell-0.15.0/lib/dcell/registries/redis_adapter.rb:40:in `set'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/dcell-0.15.0/lib/dcell/registries/redis_adapter.rb:53:in `set_node'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/dcell-0.15.0/lib/dcell/directory.rb:14:in `set'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/dcell-0.15.0/lib/dcell.rb:68:in `block in setup'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/dcell-0.15.0/lib/dcell.rb:45:in `synchronize'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/dcell-0.15.0/lib/dcell.rb:45:in `setup'
    	from /path/to/ruby/ruby/gems/2.0.0/gems/dcell-0.15.0/lib/dcell.rb:101:in `start'
    	from t.rb:3:in `<main>'

It worked properly I launch redis-server.

**Comment by niamster** [comment]
Seems like [prerequisites](https://github.com/celluloid/dcell/wiki/Prerequisites) page describes now the initial process.
