### ISSUE TITLE
Cannot get remote actor

### ISSUE THREAD

**Issue by rtacconi** [celluloid/dcell#69]
I have a :time_server actor registered with node1. In node2, which is connected to node1, I can get the list of actors on node1, but when I try to get the remote actor I get this error:

rbx-2.2.10 :060 > DCell::Node[:node1].actors
 => [:node_manager, :dcell_server, :info, :time_server]
rbx-2.2.10 :061 > DCell::Node[:node1][:time_server]
E, [2014-10-02T13:02:21.052500 #7312] ERROR -- : couldn't decode message
DCell::Server::InvalidMessageError: invalid message: dump format error
	/Users/riccardo.tacconi/.rvm/gems/rbx-2.2.10/gems/dcell-0.16.0/lib/dcell/server.rb:59:in `decode_message'
	/Users/riccardo.tacconi/.rvm/gems/rbx-2.2.10/gems/dcell-0.16.0/lib/dcell/server.rb:38:in `handle_message'
	/Users/riccardo.tacconi/.rvm/gems/rbx-2.2.10/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/Users/riccardo.tacconi/.rvm/gems/rbx-2.2.10/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
	/Users/riccardo.tacconi/.rvm/gems/rbx-2.2.10/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `invoke'
	/Users/riccardo.tacconi/.rvm/gems/rbx-2.2.10/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `task'
	/Users/riccardo.tacconi/.rvm/gems/rbx-2.2.10/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `task'
	/Users/riccardo.tacconi/.rvm/gems/rbx-2.2.10/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `initialize'
	/Users/riccardo.tacconi/.rvm/gems/rbx-2.2.10/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `create'
	kernel/bootstrap/proc.rb:20:in `call'

I am using redis and OSX

**Comment by niamster** [comment]
DCell now uses msgpack for data serialization. @jasonayre please reopen this if it still hit you.
