### ISSUE TITLE
Proposal: use "lazy pirate pattern" for req/reply

### ISSUE THREAD

**Issue by jasonayre** [celluloid/dcell#74]
I havent dug into the underlying celluloid zmq library, and am pretty zeromq noob, so forgive my ignorance if this proposal doesent work with the current architecture:

The issue Im having is similar to #70 say we have two nodes:

Node2 make request to node 1, ok
Node 1 goes down
Node2 makes another request before registry updated (node1 still exists)
Node2 hangs indefinitely until node 1 comes back up.

If node1 does not come back up, all hope is lost for node2.

I tried working around this by checking the registry for existence of node before ever invoking the remote method (and storing a number of attempts, then sleeping X seconds, then check again, before throwing error after 3), however this only works if heartbeat updates the registry before you attempt to access the remote node at all.

See https://github.com/jasonayre/cylons/blob/master/lib/cylons/agent.rb#L120 if it helps illustrate.

So it would seem to me that really the client needs to be able to account for failure to connect or send message to node, retry X attempts after X duration, at the zeromq layer, to solve. The "lazy pirate pattern" seems to describe this the closest. 

http://zguide.zeromq.org/php:chapter4#Client-Side-Reliability-Lazy-Pirate-Pattern

@tarcieri Is this a viable addition or would this somehow conflict with current architecture?

**Comment by niamster** [comment]
In pull request #91 I've implemented a mechanism to grab a bunch of actors on nodes that expose such. There's also pending git tree with ping and TTL features.
With these features it would be possible to implement a Lazy Pirate patter in the upper layer.
The problem with implementing this in DCell that it's not possible to know whether the request was properly handled before remote node died or it has to be reissued. Say you issue a request to update a database record. I have no idea how to implement transparent transaction mechanism on DCell level w/o adding lots of complexity.
In issue #89 I've expressed a possibility to put requests and responses in the Registry itself. Though I filially consider this should be implemented by the end user if needed.
So it's up to higher layer to probe and implement desired level of robustness.
We can add this pattern in the "use cases" but keep DCell as simple as possible.

**Comment by Asmod4n** [comment]
https://github.com/zeromq/malamute/blob/master/MALAMUTE.md this might also be of interest to you @niamster :)

**Comment by niamster** [comment]
thanks @Asmod4n !

**Comment by niamster** [comment]
I believe that [resolution](https://github.com/celluloid/dcell/issues/64#issuecomment-105245078) from #64 solves the problem.
