### ISSUE TITLE
dcell needs a new maintainer

### ISSUE THREAD

**Issue by tarcieri** [celluloid/dcell#87]
I am not using dcell and have no plans on using dcell in the future.

I have been trying to review and accept patches, but things have not been going well. Being unable to quickly test changes against my own systems, it seems many of the ones I have accepted have caused breakages.

There are a lot of open issues lately: #69, #70, #73, #75, #77, #79, #81, #82, #85 and I don't have time to review or help fix them.

dcell could really use a new maintainer! Is anyone interested? @niamster? @TiagoCardoso1983?

**Comment by niamster** [comment]
we can probably close this
