### ISSUE TITLE
Thoughts about the future of dcell and celluloid-zmq

### ISSUE THREAD

**Issue by Asmod4n** [celluloid/dcell#89]
dcell
====
cons
------
- depends on another process for registry needs
- no authentication
- no authorization
- connected peers can execute any ruby code
- encryption setup must be done manually
- not compatible with other languages

pros
-----
- no need to implement serialization or a rpc protocol, its just marshaled objects send to celluloid mailboxes

celluloid-zmq
====
celluloid-zmq can stay as it is right now, the zeromq maintainers said they made some mistakes with zeromq, their answer: https://github.com/zeromq/czmq. czmq is a high level zeromq binding written in c which should be the used for other language bindings.
Other notable new projects bourn around czmq:  https://github.com/zeromq/zproto, https://github.com/zeromq/zyre. zproto is a protocol generator for server and client classes in several languages around czmq based on finite state machines. zyre is a discovery framework.

czmq is rapidly approaching version 3 which adds a lot new features, i have written a wrapper for it: https://github.com/Asmod4n/ruby-ffi-czmq. I believe it should not replace celluloid-zmq.

czmq v3 api summary: https://github.com/zeromq/czmq#api-v3-summary

possbile solutions for the current cons of dcell
----
- zyre can be used for node and service discovery and for global storage
- authentication can be done with zauth
- a small DSL can be written for Celluloid Actors to white- and blacklist methods based on capabilities
- automatic configuration of encryption can be handled with zcert and zconfig
- compatibility with other languages can be achieved by using [msgpack](http://msgpack.org) for serialization and [wamp](https://github.com/tavendo/WAMP/blob/master/spec/basic.md) as the RPC protocol (only using wamp as a example, due to the usage of zeromq and zyre it can be reduced to 3 rpc calls)

While [capnproto](http://kentonv.github.io/capnproto/) looks nice I haven't yet found a c binding which could be used as a starting point for a ffi wrapper which handles serialization and rpc, the "time traveling" part also gets at least partially solved with zeromqs message batching. capnproto also has the same issue as protobuf for me: you need to learn a new type system and duplicate existing code.

I just don't know where to inject all that code.
Wrap everything into a czmq zactor written in c or ruby or better have both options in case there is no c compiler installed?
Inject most of it into celluloid actors itself?
Expand Celluloid Supervisors?

I for one would go for the czmq zactors in c and ruby so dcell can be the get go for other languages to wrap the c zactor to have a portable rpc implementation.

What would change to how it is now to users of dcell would be rather minimal, the only thing that would be missing are datatypes msgpack can't serialize.

**Comment by niamster** [comment]
To have a distributed RPC, I was thinking to store requests and responses inside the database.
Unfortunately with that zoo of supported registry adapters it's hard to maintain and support some required operations(smth like CAS). For example with Cassandra 1.x it's not possible to have smth like SETGET in Redis(I've managed to do that with mongodb and zk though).
I propose to vote for a single official registry that is supported by DCell. 
The users may use their backend at their own risk.
If needed we can use few distributed databases to efficiently implement registry.
IMHO, Redis is good enough to efficiently implement DCell registry.

**Comment by tarcieri** [comment]
I am +1 on a single official registry type, however -1 on Redis: it is, at best, a single point of failure.

I would suggest integrating with the 0MQ primitives for this stuff, since it's already a dependency.

**Comment by Asmod4n** [comment]
0MQ is basically a big linked queue which makes sure a message arrives at its destination under all circumstances(unless you are using pub/sub), for what would you need redis for rpc? as a queue?

**Comment by niamster** [comment]
@Asmod4n Ideally it would be the best to drop a binding between a request and a target node. I would like to put a request somewhere and in a worse case send a multicast message to the nodes that know how to handle it(or just notify the master node that does scheduling).

I haven't worked closely with 0MQ, maybe it already provides such mechanisms.

**Comment by Asmod4n** [comment]
When a receiver goes down a sender will send the message until the receiver gets up again and acknowledges the arrival.

In a typical 0MQ network there is no scheduler or broker. Unless you write one yourself.

**Comment by niamster** [comment]
That still doesn't solve a problem when server node may be down or busy for a long time.
My idea is that a first free server node serves the request(if it knows how to serve it).
That's my view of D-RPC.

**Comment by Asmod4n** [comment]
You can set timeouts for sending and recieving and then select another node which advertises it can fullfill your rpc.

https://github.com/zeromq/zyre can notify you also about a node going offline or which rpc calls etc it can handle.

**Comment by tarcieri** [comment]
@niamster Celluloid comes from a very different tradition of systems than one which operates that way.

Specifically Celluloid is a stateful system that models the world more along the lines of an object capability system, for example E/CapTP or Cap'n Proto.

In E terminology, each node in a DCell network resembles an E "vat". Actors are localized, persistent (if supervised with a registered name), and stateful (unless they crash).

For the kind of (round-robin?) scenarios you're describing, I've thought about some higher level abstraction (a `Service`?). I think there are 0MQ primitives that handle this sort of message routing.

There's a lot of questions about how this would work though:

- How do these actors manage state in a distributed system?
- Is there a leader? Should there be a leader?
- What happens when an actor crashes?

There's plenty of work in objcap systems to answer these sorts of questions. One set of principles for answering them is COVR (Composable Output-Valid Resilient Messaging)

http://www.hpl.hp.com/techreports/2014/HPL-2014-14.pdf

I think if you're trying to redesign the messaging semantics, before picking a backend you should describe the new messaging model you'd like to achieve.

**Comment by Asmod4n** [comment]
I would also recommend to read the 0MQ guide: http://zguide.zeromq.org/page:all

**Comment by gregory** [comment]
@niamster i'm also looking into a d-RPC mechanism. 
To solve that, we need some kind of centralized mailbox/queue where nodes could listen for new message(RPC call) and a way for them to publish/stream response to the listener(s)

I also thought about redis as you mentioned, and as of the SPF  you mentioned @tarcieri , redis-sentinel could help...

I'm not familiar with zmq, but sounds like it [does](http://zguide.zeromq.org/rb:rrclient) [implement](http://zguide.zeromq.org/rb:rrworker) a RPC mechanism, however sounds like there could only be one broker... (but since i've never used that, i'm may talk shit)
![](https://github.com/imatix/zguide/raw/master/images/fig17.png)

**Comment by tarcieri** [comment]
> I also thought about redis as you mentioned, and as of the SPF you mentioned @tarcieri

Redis is just the wrong tool for the job here. In fact Redis's author has been working on a separate tool "disque" for this purpose.

The basic prerequsites you need for a distributed service like this are:

- A distributed directory
- Backends registering themselves in that directory
- A healthchecking system

I know it seems rather attractive to punt that all onto Redis for simplicity's sake, but I would strongly advise against doing that.

Centralizing everything in a single point of failure is pretty orthogonal to the original design goals of this project

> redis-sentinel could help...

redis-sentinel is broken-by-design:

https://aphyr.com/posts/283-call-me-maybe-redis
https://aphyr.com/posts/307-call-me-maybe-redis-redux

**Comment by Asmod4n** [comment]
@tarcieri https://github.com/zeromq/zyre actually does just that, it is a distributed peer management system.

It can form a network of peers via udp beaconing, tcp peer-to-peer or (e)pgm multicast (i believe).
Every zyre node knows who is connected to that network, it does so via "ENTER" messages and heartbeats which can trigger a "EXIT" message, .
Each node which connects to that network can set up a list of headers, for e.g. which services it runs, thats effectively a distributed key/value store, but those headers only get send during discovery, e.G. when a node enters a network (at least the documentation says so). 
Those nodes can then form a group where they exchange messages related to that group, thats called shouting, those are "JOIN" and "LEAVE" messages.
What also exists is whispering; shouting and whispering could be used to distribute work, e.G. a parent shouts a work message to a group and says "work done" for example when the first node of that group whispers back that it completed the task.

There is no signle point of failure in a zyre network, every node can act as "broker" and/or "worker".

https://github.com/zeromq/malamute is a "Enterprise Messaging Broker", whatever that means.

**Comment by Asmod4n** [comment]
Oh, actually https://github.com/zeromq/malamute/blob/master/MALAMUTE.md looks kinda nice, the drawback is: its a broker model, when the broker goes down thats it.
There are also no ruby bindings yet.

**Comment by Asmod4n** [comment]
Apparently you can cluster malamute brokers, which is also cool :)

**Comment by MadBomber** [comment]
On Wednesday, April 15, 2015 11:21:06 PM Tony Arcieri wrote:
> The basic prerequsites you need for a distributed service like this are:
> 
> - A distributed directory
> - Backends registering themselves in that directory
> - A healthchecking system
> 

I have been experimenting with rethinkdb http://www.rethinkdb.com/

The latest v2.0.0  support a large number of distributed real-time problem 
areas.

-- 
Dewayne
  o-*

**Comment by niamster** [comment]
@MadBomber not sure rethinkdb is a good choice here as it permits data loss. It's good for collecting lots of data for analysis where you can tolerate data loss.

**Comment by dfockler** [comment]
I think implementing something like the COVR rules that @tarcieri posted would be a better way to handle messaging without resorting a single point of failure like a broker. Although this may not exist yet in ruby, which is an issue.

**Comment by tarcieri** [comment]
COVR is just a set of guidelines about how to handle message processing and checkpointing. It could be implemented as a library on top of DCell.

**Comment by niamster** [comment]
I didn't know anything about COVR before @tarcieri pointed on it but it's similar what I had in mind.
Though in the end I believe this should not be a core part of DCell. It might be implemented on top of it(same for Raft, etc.)
In fact you may have a KVS and COVR as DCell extensions.

**Comment by dfockler** [comment]
I'm starting to work on code for a COVR library in Ruby. I'll post it once I get a bit further, but the basic idea is that it is a message pipeline that can implement the COVR rules with a persistent storage backend.

**Comment by Asmod4n** [comment]
https://github.com/antirez/disque looks cool, there is also a ruby client https://github.com/soveran/disque-rb

**Comment by tarcieri** [comment]
I'm not sure what problem disque solves that in-process brokers don't already solve better. It's also "alpha quality", and Salvatore doesn't exactly have the best reputation when it comes to building distributed systems.

**Comment by niamster** [comment]
@Asmod4n looks like DCell now meets all your initial requirements in the `cons` section ;)

**Comment by gregory** [comment]
This is really good work @niamster  !!
could you update the changelog and the readme? :)

**Comment by Asmod4n** [comment]
@niamster looks great! :)

@tarcieri should this stay open?

**Comment by niamster** [comment]
@gregory I will update changes as soon as release version is ready. I'm waiting for the stable 0.16.1 release of celluloid.

**Comment by tarcieri** [comment]
@Asmod4n if you're happy with the changes, close it out

**Comment by digitalextremist** [comment]
Congratz @niamster on covering everything @Asmod4n raised. Well done! :+1:
