### ISSUE TITLE
How to use DCell to connect the remote node and use the actor?

### ISSUE THREAD

**Issue by firesky594** [celluloid/dcell#98]
Hello,I am a newer. I want to know how to connect remote ip by DCell.Maybe that is a simple question for you!!!Could Any one can reply ?
such as in my computer is my_ip and the remote server machine is remote_ip.
should it be right to do ?

The code in my local computer
require 'dcell'
DCell.start :id => "node1", :addr => "tcp://my_ip:4001",:directory => {:id => 'remote_node',:addr => 'tcp://remote_ip:4002'}

The code in my remote computer
require 'dcell'
DCell.start :id => "remote_node", :addr => "tcp://remote_ip:4002"

How to do?

**Comment by digitalextremist** [comment]
Hello @firesky594, please ask about this on the Google Group:

https://groups.google.com/forum/#!forum/celluloid-ruby

This issue tracker is for bugs and feature requests.

**Comment by niamster** [comment]
Hello @firesky594,
on the server node you have to setup DCell with real IP(externally visible), on the client you don't have to setup anything as it should discover the server node via registry.

**Comment by firesky594** [comment]
Hello  @digitalextremist , I am sorry..I use github  for a short time :)
Hello @niamster , Is it like this?
On the server:
DCell.start :id => "remote", :addr => "tcp://real_IP:1234",    
    :registry => {
        :adapter => 'redis',
        :server => 'real_IP',
        :port => 6379
    }
On the client : 
DCell.start :id => "local", :addr => "tcp://local_IP:1234",    
    :registry => {
        :adapter => 'redis',
        :server => 'real_IP',
        :port => 6379
    }
Thank for reply :)

**Comment by niamster** [comment]
Hello @firesky594 
If you are using current master the server will look like:
```ruby
require 'dcell'
require 'dcell/registries/redis_adapter'

registry = DCell::Registry::RedisAdapter.new redis_options
DCell.start id: 'remote', registry: registry
```
And for the client as simple as
```ruby
require 'dcell'
require 'dcell/registries/redis_adapter'

registry = DCell::Registry::RedisAdapter.new redis_options
DCell.start registry: registry
remote = DCell::Node['remote']
```

Where `redis_options` correspond to the native options of [redis-rb](https://github.com/redis/redis-rb) GEM.

Check out examples in DCell repo.
